version: '3.1'
services:
  mysql:
    container_name: mysql-3306
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql-homework
    ports:
      - "3306:3306"
  redis:
    container_name: redis-6379
    image: redis
    restart: always
    ports:
      - "6379:6379"
