server:
  port: 8091
spring:
  mvc:
    path match:
      matching-strategy: ant_path_matcher
  redis:
    host: TODO
    port: TODO
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: TODO
    username: TODO
    password: TODO
    druid:
      initial-size: 5
      max-active: 20
      max-wait: 60000
      min-idle: 1
      validation-query: select 1
  devtools:
    restart:
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: jz.cbq.backend.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
logging:
  level:
    jz:
      cbq:
        backend:
          mapper: debug
adminSecret: TODO